### PR TITLE
There it goes

### PR DESCRIPTION
**Pull request by pt300**
Added a mathematical way of scaling background to fit perfectly to the viewport
Made drag action stop after mouse leaves window

### CODE REVIEW

**Comment by pt300** [comment]
I suck with git

**Comment by pt300** [comment]
fixxd

**Comment by pt300** [comment]
I just spotted a literally retarded mistake

**Comment by sKiLdUsT** [comment]
1. Listening on "mouseout" event to stop dragging is wrong, as it unintendedly stops the dragging process when dragging outside the browser window and the user would have to repeatedly drag, which is annoying for users with multiple screens like me.
2. Your code isn't ES2015 compliant. (Should probably set up some style guidelines)

**Comment by pt300** [comment]
And still no?

**Pull request closed without merging**
